=== mwladysiak/VectorTileMap/VectorTileMap/src/org/oscim/theme/renderTheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://mapsforge.org/renderTheme" xmlns:tns="http://mapsforge.org/renderTheme"
	elementFormDefault="qualified" xml:lang="en">
	<!-- attribute types -->
	<xs:simpleType name="cap">
		<xs:restriction base="xs:string">
			<xs:enumeration value="butt" />
			<xs:enumeration value="round" />
			<xs:enumeration value="square" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="closed">
		<xs:restriction base="xs:string">
			<xs:enumeration value="yes" />
			<xs:enumeration value="no" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="color">
		<xs:restriction base="xs:string">
			<xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="elementList">
		<xs:restriction base="xs:string">
			<xs:enumeration value="node" />
			<xs:enumeration value="way" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontFamily">
		<xs:restriction base="xs:string">
			<xs:enumeration value="default" />
			<xs:enumeration value="default_bold" />
			<xs:enumeration value="monospace" />
			<xs:enumeration value="sans_serif" />
			<xs:enumeration value="serif" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontStyle">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bold" />
			<xs:enumeration value="bold_italic" />
			<xs:enumeration value="italic" />
			<xs:enumeration value="normal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonNegativeFloat">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="src">
		<xs:restriction base="xs:string">
			<xs:pattern value="(jar|file)\:.+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="strokeDasharray">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="textKey">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ele" />
			<xs:enumeration value="addr:housenumber" />
			<xs:enumeration value="name" />
			<xs:enumeration value="ref" />
		</xs:restriction>
	</xs:simpleType>


	<!-- rendering instructions -->
	<xs:complexType name="area">
			<xs:attribute name="name" type="xs:string" use="optional"
			default="0" />
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="fill" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="0" />
		<xs:attribute name="fade" type="xs:integer" use="optional"
			default="-1" />
		<xs:attribute name="blend" type="xs:integer" use="optional"
			default="-1" />
		<xs:attribute name="blend-fill" type="tns:color" use="optional"
			default="#000000" />
	</xs:complexType>

	<xs:complexType name="caption">
		<xs:attribute name="k" type="tns:textKey" use="required" />
		<xs:attribute name="dy" type="xs:float" use="optional"
			default="0" />
		<xs:attribute name="font-family" type="tns:fontFamily"
			use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional"
			default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat"
			use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="circle">
		<xs:attribute name="r" type="tns:nonNegativeFloat" use="required" />
		<xs:attribute name="scale-radius" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="fill" type="tns:color" use="optional"
			default="#00000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="line">
		<!-- named style -->
		<xs:attribute name="name" type="xs:string" use="optional"
			default="0" />
		<!-- inherited style -->
		<xs:attribute name="from" type="xs:string" use="optional"
			default="0" />
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="width" type="xs:float"
			use="optional" default="0" />
		<!-- minimum scaled width to draw outline -->
		<xs:attribute name="min" type="xs:float"
			use="optional" default="0" />
		<xs:attribute name="stroke-dasharray" type="tns:strokeDasharray"
			use="optional" />
		<xs:attribute name="cap" type="tns:cap" use="optional"
			default="round" />
		<xs:attribute name="outline" type="xs:integer" use="optional"
			default="0" />
		<xs:attribute name="fade" type="xs:integer" use="optional"
			default="-1" />
		<xs:attribute name="blur" type="xs:float" use="optional"
			default="-1" />
		<xs:attribute name="fixed" type="xs:boolean" use="optional"
			default="false" />
	</xs:complexType>

<!--  <xs:complexType name="outline">
		<xs:attribute name="name" type="xs:string" use="optional"
			default="0" />
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="0" />
	</xs:complexType>
-->
	<xs:complexType name="lineSymbol">
		<xs:attribute name="src" type="tns:src" use="required" />
		<xs:attribute name="align-center" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="repeat" type="xs:boolean" use="optional"
			default="false" />
	</xs:complexType>

	<xs:complexType name="text">
		<xs:attribute name="name" type="xs:string" use="optional"
			default="0" />
		<xs:attribute name="style" type="xs:string" use="optional"
			default="0" />
		<xs:attribute name="k" type="tns:textKey" use="optional" default="name"/>
		<xs:attribute name="dy" type="xs:float" use="optional"
			default="0" />
		<xs:attribute name="font-family" type="tns:fontFamily"
			use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional"
			default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat"
			use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional"
			default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="0" />
		<xs:attribute name="caption" type="xs:boolean" use="optional"
			default="false" />
	</xs:complexType>

	<xs:complexType name="symbol">
		<xs:attribute name="src" type="tns:src" use="required" />
	</xs:complexType>


	<!-- rule elements -->
	<xs:complexType name="rule">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- recursion to allow for nested rules -->
			<xs:element name="rule" type="tns:rule" />

			<xs:element name="area" type="tns:area" />
			<xs:element name="use-area" type="tns:area" />
			<xs:element name="caption" type="tns:caption" />
			<xs:element name="circle" type="tns:circle" />
			<xs:element name="line" type="tns:line" />
			<xs:element name="use-line" type="tns:line" />
			<xs:element name="outline" type="tns:line" />
			<xs:element name="use-outline" type="tns:line" />
			<xs:element name="lineSymbol" type="tns:lineSymbol" />
			<xs:element name="text" type="tns:text" />
			<xs:element name="use-text" type="tns:text" />
			<!-- <xs:element name="styletext type="xs:string" /> -->
			<xs:element name="symbol" type="tns:symbol" />
			<!-- outline is defined within rules to match layering -->
			<xs:element name="style-outline" type="tns:line" />
		</xs:choice>
		<xs:attribute name="e" type="tns:elementList" use="required" />
		<xs:attribute name="k" type="xs:string" use="required" />
		<xs:attribute name="v" type="xs:string" use="required" />
		<xs:attribute name="closed" type="tns:closed" use="optional"
			default="any" />
		<xs:attribute name="zoom-min" type="xs:unsignedByte" use="optional"
			default="0" />
		<xs:attribute name="zoom-max" type="xs:unsignedByte" use="optional"
			default="127" />
	</xs:complexType>


	<!-- rendertheme element -->
	<xs:complexType name="rendertheme">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:sequence minOccurs="0" maxOccurs="256">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="style-text" type="tns:text" />
					<xs:element name="style-area" type="tns:area" />
					<xs:element name="style-line" type="tns:line" />
					<xs:element name="style-outline" type="tns:line" />
				</xs:choice>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
			
				<xs:element name="rule" type="tns:rule" />				
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="version" type="xs:positiveInteger"
			use="required" />
		<xs:attribute name="map-background" type="tns:color" use="optional"
			default="#ffffff" />
		<xs:attribute name="base-stroke-width" type="tns:nonNegativeFloat"
			use="optional" default="1" />
		<xs:attribute name="base-text-size" type="tns:nonNegativeFloat"
			use="optional" default="1" />
	</xs:complexType>


	<!-- root element -->
	<xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== mwladysiak/VectorTileMap/VectorTileMap/src/org/oscim/theme/styles/tronrender.xml
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns="http://mapsforge.org/renderTheme"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://mapsforge.org/renderTheme ../renderTheme.xsd"
             version="1" map-background="#050508">

  <style-text name="road" k="name"    font-style="bold"  font-size="18" stroke="#606050" fill="#eeffee" stroke-width="2.5" />
  <style-text name="major-road" k="name" font-style="bold" font-size="19" fill="#e2cf5d" stroke="#101010" stroke-width="2.5" />
  
  <style-area name="residential"         fill="#ff0000" fade="10"/>
  
  <style-area name="railway|industrial"  fill="#f2eeef" fade="10"/>
  <!-- "#f0fae7" mint green  -->
  <style-area name="farmland"            fill="#fff8bf" fade="11" />
  
  <!-- fade out at z=7, blend over to 'blend-fill' in z=11 -->
  <style-area name="forest|wood"         fill="#151806" fade="7" blend="11" blend-fill="#1e2205"/> 
 
  <!-- grass|meadow|garden|grassland|scrub -->
 	<style-area name="greens"              fill="#33390c" fade="10" />
 	
 	<!-- marsh|wetland|nature_reserve -->
 	<style-area name="greens2"             fill="#627100" fade="12" />
 	  
 	<!-- park|common|green|cemetery|golf_course|dog_park -->
 	<style-area name="park"                fill="#627100" fade="11" />
  
  <!-- de:Kleingartengebiet -->
  <style-area name="allotments"          fill="#efeae0" fade="12" />
 	
 	<!-- de:Steinbruch, Schotter-, Kies-, Sand- und Tongrube -->
  <style-area name="quarry"              fill="#ddddcc" fade="10" />
  
  <style-area name="military"            fill="#eeedea" fade="10"/>
  
  
  <style-line name="residential"         stroke="#ffffff" width="1.0" blur="1.0" fade="13"/>
 	<style-line name="residential:bridge"  from="residential" cap="square"/>
 	
 	<!-- when inheriting another style with 'from' then 'witdth' is meant relative to the parent -->
 	<style-line name="pedestrian"          from="residential" width="-0.4"/>
  <style-line name="pedestrian:bridge"   from="pedestrian" cap="square"/>
  	
  <style-line name="highway:z11"         stroke="#fcba5a" width="1.8" blur="0.9"/>
  <!-- <style-line name="highway:z11:bridge"    from="highway:z11" cap="butt" /> -->
  
  <style-line name="trunk_link"          stroke="#fee16e" width="1.3" cap="butt" blur="0.9"/>
  <style-line name="trunk"               stroke="#fedb52" width="1.6" blur="0.9"/>
  <style-line name="primary:z11"         stroke="#f2df6d" width="1.5" blur="0.9"/>
  <style-line name="secondary:z11"       from="primary:z11" width="-0.1"/>
   
  <style-line name="tertiary"            from="residential" width="0.2" fade="11"/>
  <style-line name="construction"        stroke="#e0e0e0" width="1.2" />

  <style-line name="highway-service"     from="residential" width="-0.6" />
    
  <!-- track|footway|path|cycleway -->
  <style-line name="footway"             stroke="#c1bcb6" width="1.2" cap="butt" fixed="true"/>
  <style-line name="footway:z16"         from="footway" width="-1.0" fixed="false" fade="-1"/>
  <style-line name="footway:z17"         stroke="#faf8f5" width="0.3"/>
  
  <!-- de: ein Weg der fÃ¼r Reiter vorgeshen ist.. -->
  <style-line name="bridleway"           stroke="#d3cb98" width="0.4" cap="butt"/>  
  
  <style-line name="steps"               stroke="#f1f0f4" width="0.25" cap="butt" />
  
  <style-line name="water:outline"       stroke="#a4bbcc" width="1.0" cap="butt" /> 
	<style-line name="water"               stroke="#cca4bbcc" width="0.6" cap="butt" /> 
  <style-area name="water"               fill="#001223" />
  <!-- no-go area boundary -->
  <style-line name="fence"               stroke="#444444" width="1.2" fixed="true" cap="butt"/>
 	
  <style-line name="aeroway:runway"      stroke="#008888" width="1.8" cap="butt" blur="0.7" />
  
  <style-line name="building"            stroke="#dd888888" width="1.5" fixed="true" cap="butt"/> 
  <style-area name="building"            fill="#ee202020" fade="15"/>
  
  <!-- ways -->
  <rule e="way" k="*" v="*" >

    <rule e="way" k="natural"  v="grassland|scrub" zoom-min="10">
      <use-area name="greens"/>
    </rule>
      
    <!-- landuse base -->      
    <rule e="way" k="landuse" v="*">
     
  <!--    <rule e="way" k="*"  zoom-min="10" v="farmland|farm|orchard|vineyard|greenhouse_horticulture|plant_nursery">
        <use-area name="farmland"/>
      </rule>
     
       <rule e="way" k="*"  v="quarry">
        <use-area name="quarry"/>
      </rule>
       
      <rule e="way" k="*" v="residential|farmyard|retail|commercial|industrial;retail">
        <use-area name="residential" />
      </rule>

      <rule e="way" k="*" v="industrial|railway"> 
         <use-area name ="railway|industrial"/>
      </rule>
-->
     <!--   <rule e="way" k="*" v="military">
				 <use-area name="military"/>
      </rule> -->
      
      <!--<rule e="way" k="landuse" v="construction|greenfield"> <area fill="#a47c41" 
         stroke="#e4e4e4" width="0.2" /> </rule> -->
      <!-- <rule e="way" k="landuse" v="garages"> <area fill="#d6d6e4" /> </rule> -->
    </rule>

   
		
	  <rule e="way" k="landuse|natural|leisure||amenity" v="*">
			<!-- kind of more like landuse imho -->
		  <rule e="way" k="leisure|landuse" v="nature_reserve">
		    <use-area name="greens2" />
		    <rule e="way" k="*" v="*" zoom-min="14">
		       <line stroke="#abe29c" width="1.0" fixed="true" cap="butt" />
	      </rule>
	    </rule>
	  
	    <!-- landuse -->
	    <rule e="way" k="landuse" v="*"  zoom-min="11">
	      <!-- how about 'leisure' for this one? -->
	      <rule e="way" k="*" v="cemetery">
	        <use-area name="park"/>
	      </rule>
	           
	      <rule e="way" k="*" v="reservoir|basin">
	        <use-area name="water" />
	      </rule>
	    </rule>
	
	    <rule e="way" k="landuse" v="village_green|recreation_ground" >
	      <use-area name="greens" />
	    </rule>
	   
	   <!--  <rule e="way" k="landuse" v="allotments" zoom-min="12">
	     <use-area name="allotments"/>
	    </rule>-->
	
	    <rule e="way" k="leisure" v="park|common|green|golf_course|dog_park" zoom-min="11">
	      <use-area name="park"/>
	    </rule>
	          
	       <!-- Heideland, keep below forest -->
	    <rule e="way" k="*" zoom-min="11" v="heath|sand">
	      <area fill="#0f0f0c" fade="11" />
	    </rule>
	      
	    <rule e="way" k="landuse" v="forest">
	         <use-area name="forest|wood"/>
	    </rule>
	   
	    <rule e="way" k="natural" v="wood">
	          <use-area name="forest|wood"/>
	        <!--  <line stroke="#abcfab" width="1.5" fixed="true" cap="butt"/> -->
	    </rule>
	    
			<!-- keep grass above forest:wood and leisure:park! --> 
			<rule e="way" k="landuse"  v="grass|meadow">
			   <use-area name="greens"/>
	    </rule>
	    
	    <rule e="way" k="leisure"  v="garden">
		    <use-area name="greens"/>
	    </rule>
	     
	
	    <rule e="way" k="leisure" v="track">
	       <line stroke="#c1bcb6" width="1.3" cap="butt"  fixed="true" />
	    </rule>
	            
	    <!-- amenity -->
	    <rule e="way" k="amenity" v="*">
	     <rule e="way" k="*" v="kindergarten|school|college|university" zoom-min="14"> 
	        <area fill="#cdabde" stroke="#b094bf" stroke-width="0.2" /> </rule>
	           
	      <rule e="way" k="*" v="parking" zoom-min="14">
	        <area fill="#444434" stroke="#d4d4d4" stroke-width="0.2" />
	      </rule>
	      
	      <rule e="way" k="*" v="fountain" closed="yes">
	        <area fill="#b4cbdc" stroke="#000080" stroke-width="0.15" />
	      </rule>
	    </rule>
	
	    <!-- <rule e="way" k="natural" v="coastline">
	      <line stroke="#a4bbcc" width="1.2" fixed="true" />
	    </rule> -->
	
	    <!-- natural -->
	    <rule e="way" k="natural" v="*" zoom-min="10">
	
	      <rule e="way" k="*" v="glacier">
	        <area fill="#fafaff" />
	      </rule>
	      <rule e="way" k="*" v="land">
	        <area fill="#080808" />
	      </rule>
	      
	     <!--  <rule e="way" k="*" v="beach">
	          <area fill="#aaedd400"/>
	        <line stroke="#fce94f" fixed="true" width="2.8" />
	      </rule>-->
	   
	      <rule e="way" k="*" v="marsh|wetland|mud">
	         <use-area name="greens2" />
	      </rule>
	    </rule>
	
	
	    <!-- leisure -->
	    <rule e="way" k="leisure" v="*" zoom-min="13">
	
	      <rule e="way" k="*" v="stadium" >
	        <area fill="#404040"  />
	          	        <line stroke="#cccccc" width="1.0" fixed="true" cap="butt" />
	      </rule>
	      
	      <!--should be under playing field -->
	      <!--  <rule e="way" k="*" zoom-min="14" v="sports_centre|water_park">
	        <area fill="#daefdb" fade="12" />
	      </rule>
	     
	      <rule e="way" k="*" zoom-min="15" v="playground|miniature_golf">
	        <area fill="#f4f4de" />
	        <line stroke="#fbdbc8" width="0.6" fixed="true" cap="butt" />
	      </rule>
	      
	      <rule e="way" k="*" v="playing_fields|pitch">
	        <area fill="#f4f4de" />
	        <line stroke="#dbdbc8" width="0.6" fixed="true" cap="butt" />
	      </rule>
	-->
	      <rule e="way" k="*" v="swimming_pool">
	        <area fill="#b4cbdc" stroke="#6060ff" stroke-width="0.2" />
	      </rule>
	      
	      <!-- <rule e="way" k="*" v="track"> <rule e="way" k="area" v="yes|true"> 
	           <area fill="#c9d8a2" stroke="#b7c690" width="0.025" /> </rule> <rule 
	           e="way" k="area" v="~|no|false"> <line stroke="#b7c690" width="0.75" 
	           /> </rule> </rule> -->
	    </rule>
	
	    
	     <!-- area outlines need to be above to avoid uggly pixelation where 
	       not aliased polygon overlaps the lines...   -->
	       
	    <rule e="way" k="leisure|landuse" v="*" zoom-min="14">
		    
		    <rule e="way" k="*" v="nature_reserve">
		       <line stroke="#abe29c" width="1.0" fixed="true" cap="butt" />
	      </rule>
	
		    <rule e="way" k="*" v="military">
					 <use-line name="fence" />
	      </rule>
	    </rule>
    </rule>
    

	    
   
    <!-- waterways -->
